//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 212.150301 on Stable branch
// Generated with ALiVE version 1.19.0.2301051
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_TEST {
        displayName = "[TEST] my faction";
        side = 1;
        flag = "\A3\ui_f\data\map\markers\flags\nato_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\nato_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class WEST {

        class B_TEST {
            name = "[TEST] my faction";

            class Infantry {
                name = "Infanterie";

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class RPIMA {
                name = "1er RPiMa";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class B_Soldier_F;
    class B_Soldier_F_OCimport_01 : B_Soldier_F { scope = 0; class EventHandlers; };
    class B_Soldier_F_OCimport_02 : B_Soldier_F_OCimport_01 { class EventHandlers; };


    class B_TEST_Unit_01 : B_Soldier_F_OCimport_02 {
        author = "Florian";
        scope = 2;
        scopeCurator = 2;
        displayName = "Unit";
        side = 1;
        faction = "B_TEST";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "U_B_CombatUniform_mcam";

        linkedItems[] = {"V_PlateCarrier1_rgr","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles"};
        respawnlinkedItems[] = {"V_PlateCarrier1_rgr","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles"};

        weapons[] = {"arifle_MX_ACO_pointer_F","hgun_P07_F"};
        respawnWeapons[] = {"arifle_MX_ACO_pointer_F","hgun_P07_F"};

        magazines[] = {"30Rnd_65x39_caseless_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_mag","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"arifle_MX_ACO_pointer_F","","acc_pointer_IR","optic_Aco",{"30Rnd_65x39_caseless_mag",30},{},""},{},{"hgun_P07_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"U_B_CombatUniform_mcam",{{"FirstAidKit",1},{"30Rnd_65x39_caseless_mag",2,30}}},{"V_PlateCarrier1_rgr",{{"30Rnd_65x39_caseless_mag",7,30},{"16Rnd_9x21_Mag",2,17},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{},"H_HelmetB","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TEST_Unit_02 : B_TEST_Unit_01 {
        author = "Florian";
        scope = 2;
        scopeCurator = 2;
        displayName = "Unit";
        side = 1;
        faction = "B_TEST";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "rhs_uniform_g3_m81";

        linkedItems[] = {"rhsusf_plateframe_marksman","rhsusf_opscore_mar_ut_pelt","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsusf_plateframe_marksman","rhsusf_opscore_mar_ut_pelt","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_mk17_CQC","rhsusf_weap_glock17g4"};
        respawnWeapons[] = {"rhs_weap_mk17_CQC","rhsusf_weap_glock17g4"};

        magazines[] = {"rhs_mag_20Rnd_SCAR_762x51_m80a1_epr","rhsusf_mag_17Rnd_9x19_FMJ","rhs_mag_20Rnd_SCAR_762x51_m80a1_epr","rhsusf_mag_17Rnd_9x19_FMJ"};
        respawnMagazines[] = {"rhs_mag_20Rnd_SCAR_762x51_m80a1_epr","rhsusf_mag_17Rnd_9x19_FMJ","rhs_mag_20Rnd_SCAR_762x51_m80a1_epr","rhsusf_mag_17Rnd_9x19_FMJ"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_mk17_CQC","","rhsusf_acc_anpeq15side","rhsusf_acc_su230a_c",{"rhs_mag_20Rnd_SCAR_762x51_m80a1_epr",20},{},"rhsusf_acc_tdstubby_tan"},{},{"rhsusf_weap_glock17g4","","","",{"rhsusf_mag_17Rnd_9x19_FMJ",17},{},""},{"rhs_uniform_g3_m81",{{"rhsusf_ANPVS_15",1},{"rhs_Booniehat_m81",1},{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1}}},{"rhsusf_plateframe_marksman",{{"rhsusf_acc_aac_scarh_silencer",1},{"rhs_mag_20Rnd_SCAR_762x51_m80a1_epr",5,20},{"rhsusf_mag_17Rnd_9x19_FMJ",2,17},{"rhs_mag_an_m8hc",1,1},{"rhs_mag_mk84",1,1},{"rhs_mag_m67",2,1},{"Chemlight_red",3,1}}},{},"rhsusf_opscore_mar_ut_pelt","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};